# Generated by Django 5.2.17 on 2026-09-12 20:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='empresa pagadora')),
            ],
            options={
                'verbose_name': 'empresa pagadora',
                'verbose_name_plural': 'empresas pagadoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='setor solicitante')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão na importação')),
            ],
            options={
                'verbose_name': 'setor solicitante',
                'verbose_name_plural': 'setores solicitantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inss_rate', models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='INSS (%)')),
                ('iss_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='ISS (%)')),
                ('ir_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='IR (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alíquotas',
                'verbose_name_plural': 'alíquotas',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='unidade')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão na importação')),
                ('paying_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalog.payingcompany', verbose_name='empresa pagadora')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['name'],
            },
        ),
    ]
