# Generated by Django 5.2.17 on 2026-09-12 20:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicators', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='arquivo')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('APLICADOR', 'Aplicador'), ('ORIENTADOR', 'Orientador'), ('VOLANTE', 'Volante')], default='APLICADOR', max_length=12, verbose_name='função')),
                ('activity_date', models.DateField(verbose_name='data da atividade')),
                ('event_name', models.CharField(max_length=150, verbose_name='prova/evento')),
                ('segment', models.CharField(blank=True, max_length=80, verbose_name='segmento')),
                ('shift', models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=6, verbose_name='horário')),
                ('payment_date', models.DateField(verbose_name='data de pagamento')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor líquido')),
                ('gross_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='valor bruto (RPA)')),
                ('inss_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='INSS')),
                ('iss_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='ISS')),
                ('ir_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='IR')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='applicators.applicator', verbose_name='aplicador')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='payroll.importbatch')),
                ('paying_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.payingcompany', verbose_name='empresa pagadora')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sector', verbose_name='setor solicitante')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['-activity_date', 'applicator__full_name'],
            },
        ),
    ]
