# Generated by Django 5.2.17 on 2026-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_serviceentry_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, upload_to='imports/%Y/%m/', verbose_name='planilha original'),
        ),
    ]