# Generated by Django 5.2.17 on 2026-09-21 12:33

from django.conf import settings
from django.db import migrations, models

from apps.payroll.models import event_key


def fill_event_key(apps, schema_editor):
    """Preenche a chave canônica do evento nos lançamentos que já existem."""
    ServiceEntry = apps.get_model("payroll", "ServiceEntry")
    for entry in ServiceEntry.objects.all().iterator():
        entry.event_key = event_key(entry.event_name)
        entry.save(update_fields=["event_key"])


def drop_duplicate_entries(apps, schema_editor):
    """Apaga as repetições que entraram antes de a restrição existir.

    O mesmo serviço foi lançado mais de uma vez porque a operação reaproveita a
    planilha da semana anterior e alguma aba fica com a data antiga — a
    importação de 14/09 e a de 15/09 trouxeram de volta as oficinas de 08/09.
    Fica o lançamento mais antigo de cada grupo, que é o do lote que
    registrou o serviço primeiro; os seguintes são cópias dele e, enquanto
    existirem, somam um valor a mais no pagamento da pessoa.
    """
    ServiceEntry = apps.get_model("payroll", "ServiceEntry")
    seen, doomed = set(), []
    fields = ("applicator_id", "activity_date", "event_key", "shift", "role", "unit_id")
    for entry in ServiceEntry.objects.order_by("pk").iterator():
        identity = tuple(getattr(entry, field) for field in fields)
        if identity in seen:
            doomed.append(entry.pk)
            print(
                f"  duplicata removida: #{entry.pk} {entry.event_name} "
                f"{entry.activity_date:%d/%m/%Y} {entry.shift} R$ {entry.net_amount}"
            )
            continue
        seen.add(identity)
    if doomed:
        print(f"  {len(doomed)} lançamento(s) duplicado(s) removido(s).")
        ServiceEntry.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applicators', '0004_alter_applicator_registration_status'),
        ('catalog', '0001_initial'),
        ('payroll', '0003_importbatch_source_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='event_key',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.RunPython(fill_event_key, migrations.RunPython.noop, elidable=False),
        migrations.RunPython(drop_duplicate_entries, migrations.RunPython.noop, elidable=False),
        migrations.AddConstraint(
            model_name='serviceentry',
            constraint=models.UniqueConstraint(fields=('applicator', 'activity_date', 'event_key', 'shift', 'role', 'unit'), name='entry_one_service_per_shift'),
        ),
    ]