# Generated by Django 5.2.17 on 2026-09-13 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicators', '0001_initial'),
        ('catalog', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='activity_date',
            field=models.DateField(db_index=True, verbose_name='data da atividade'),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='payment_date',
            field=models.DateField(db_index=True, verbose_name='data de pagamento'),
        ),
        migrations.AddIndex(
            model_name='serviceentry',
            index=models.Index(fields=['payment_date', 'applicator'], name='entry_paydate_applicator'),
        ),
    ]