# Generated by Django 5.2.17 on 2026-09-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=150, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='curso')),
                ('institution', models.CharField(blank=True, max_length=120, verbose_name='instituição')),
                ('bank_name', models.CharField(blank=True, max_length=80, verbose_name='banco')),
                ('bank_branch', models.CharField(blank=True, max_length=10, verbose_name='agência')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='conta')),
                ('pix_key', models.CharField(blank=True, max_length=120, verbose_name='chave PIX')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('needs_review', models.BooleanField(default=False, verbose_name='cadastro incompleto')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aplicador',
                'verbose_name_plural': 'aplicadores',
                'ordering': ['full_name'],
            },
        ),
    ]
