# Generated by Django 5.2.17 on 2026-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicator',
            name='needs_review',
        ),
        migrations.AddField(
            model_name='applicator',
            name='registration_status',
            field=models.CharField(choices=[('ativo', 'cadastro ativo: pagamento recorrente'), ('novo', 'cadastro novo: primeiro pagamento')], default='ativo', max_length=10, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]