# Generated by Django 5.2.17 on 2026-09-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicators', '0002_remove_applicator_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicator',
            name='account_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='tipo de conta'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='course_period',
            field=models.CharField(blank=True, max_length=20, verbose_name='período'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='identity_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='identidade'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=80, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='photo',
            field=models.CharField(blank=True, help_text='Caminho em static/, ex.: "img/aplicadores/fulano.jpeg".', max_length=120, verbose_name='foto 3x4'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='pis_nit',
            field=models.CharField(blank=True, max_length=30, verbose_name='PIS/NIT'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='pix_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='tipo de chave PIX'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='referral',
            field=models.CharField(blank=True, max_length=120, verbose_name='indicação'),
        ),
        migrations.AddField(
            model_name='applicator',
            name='vse',
            field=models.BooleanField(default=False, verbose_name='VSE'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=20, verbose_name='agência'),
        ),
    ]