# Generated by Django 5.2.17 on 2026-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicators', '0003_applicator_account_type_applicator_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicator',
            name='registration_status',
            field=models.CharField(choices=[('ativo', 'cadastro ativo: pagamento recorrente'), ('novo', 'cadastro novo: primeiro pagamento')], default='novo', max_length=10, verbose_name='situação'),
        ),
    ]